spring:
  application:
    name: ImoocMerchants
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/passbook?serverTimezone=UTC&autoReconnect=true
    username: root
    password: '00000000'
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: imooc-merchants.log
